language: ruby
rvm:
  - 2.3.1

bundler_args: --without production

env:
  global:
    - CC_TEST_REPORTER_ID=82fff89ba0da7030cf339a100c267baf4fdef4dd1c534490e9dc0d95fe48cf34
    - github_key=test
    - github_secret=test

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

script:
  - bundle exec rake db:setup
  - bundle exec rspec
  - $CC format-coverage --output coverage/codeclimate.$SUITE.json
  - bundle exec cucumber
  - $CC format-coverage --output coverage/codeclimate.$SUITE.json

after_script:
  - $CC sum-coverage coverage/codeclimate.*.json | $CC upload-coverage
  - $CC after-build --exit-code $TRAVIS_TEST_RESULT